# Generated by Django 5.2.3 on 2025-06-13 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido para Revisão'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=10, verbose_name='Status do Plano')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('form_data', models.JSONField(default=dict, verbose_name='Dados do Formulário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmos', to=settings.AUTH_USER_MODEL, verbose_name='Produtor Responsável')),
            ],
            options={
                'verbose_name': 'Plano de Manejo Orgânico',
                'verbose_name_plural': 'Planos de Manejo Orgânico',
                'ordering': ['-updated_at'],
            },
        ),
    ]
