# Generated by Django 5.2.3 on 2025-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_pmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmo',
            name='nome_identificador',
            field=models.CharField(default='Plano de Manejo sem nome', max_length=200),
        ),
        migrations.AlterField(
            model_name='pmo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido para Revisão'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=500, verbose_name='Status do Plano'),
        ),
    ]
